version: "3.5"
services:
  api:
    image: theramblingrover/amo_api_test:latest
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - secret_vol:/app/secrets/
    ports:
      - 58000:8000

    command: uvicorn amo_test_task.asgi:application --host 0.0.0.0

volumes:
  secret_vol: